hibernate.connection.driver_class=com.mysql.cj.jdbc.Driver
hibernate.connection.url=jdbc:mysql://localhost:3307/campaign_db
hibernate.connection.username=campaign_user
hibernate.connection.password=campaign_password
hibernate.dialect=org.hibernate.dialect.MySQLDialect
