hibernate.connection.driver_class=com.mysql.cj.jdbc.Driver
hibernate.connection.url=jdbc:mysql://localhost:3308/auth_db
hibernate.connection.username=auth_user
hibernate.connection.password=auth_password
hibernate.dialect=org.hibernate.dialect.MySQLDialect
