package com.kingroly.authservice.model;
// Generated 18 set 2026, 10:37:53 by Hibernate Tools 6.2.8.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import java.util.HashSet;
import java.util.Set;

/**
 * Advertisers generated by hbm2java
 */
@Entity
@Table(name="advertisers"
    ,catalog="auth_db"
    , uniqueConstraints = {@UniqueConstraint(columnNames="company_name"), @UniqueConstraint(columnNames="email")} 
)
public class Advertisers  implements java.io.Serializable {


     private Long id;
     private String companyName;
     private String email;
     private String password;
     private String role;
     private Set<RefreshTokens> refreshTokenses = new HashSet<RefreshTokens>(0);
     private Set<OtpCodes> otpCodeses = new HashSet<OtpCodes>(0);
     private Set<DeviceSessions> deviceSessionses = new HashSet<DeviceSessions>(0);
     private Set<PasswordResetTokens> passwordResetTokenses = new HashSet<PasswordResetTokens>(0);

    public Advertisers() {
    }

    public Advertisers(String companyName, String email, String password, String role, Set<RefreshTokens> refreshTokenses, Set<OtpCodes> otpCodeses, Set<DeviceSessions> deviceSessionses, Set<PasswordResetTokens> passwordResetTokenses) {
       this.companyName = companyName;
       this.email = email;
       this.password = password;
       this.role = role;
       this.refreshTokenses = refreshTokenses;
       this.otpCodeses = otpCodeses;
       this.deviceSessionses = deviceSessionses;
       this.passwordResetTokenses = passwordResetTokenses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="company_name", unique=true, nullable=false, length=255)
    public String getCompanyName() {
        return this.companyName;
    }
    
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    
    @Column(name="email", unique=true, nullable=false, length=255)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="password", nullable=false, length=255)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="role", length=50)
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="advertisers")
    public Set<RefreshTokens> getRefreshTokenses() {
        return this.refreshTokenses;
    }
    
    public void setRefreshTokenses(Set<RefreshTokens> refreshTokenses) {
        this.refreshTokenses = refreshTokenses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="advertisers")
    public Set<OtpCodes> getOtpCodeses() {
        return this.otpCodeses;
    }
    
    public void setOtpCodeses(Set<OtpCodes> otpCodeses) {
        this.otpCodeses = otpCodeses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="advertisers")
    public Set<DeviceSessions> getDeviceSessionses() {
        return this.deviceSessionses;
    }
    
    public void setDeviceSessionses(Set<DeviceSessions> deviceSessionses) {
        this.deviceSessionses = deviceSessionses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="advertisers")
    public Set<PasswordResetTokens> getPasswordResetTokenses() {
        return this.passwordResetTokenses;
    }
    
    public void setPasswordResetTokenses(Set<PasswordResetTokens> passwordResetTokenses) {
        this.passwordResetTokenses = passwordResetTokenses;
    }




}


